### ISSUE TITLE
Add Funding Opportunities

### ISSUE THREAD

**Issue by mbwatson** [fabric-testbed/fabric-website#38]
to contact page, add funding opportunities list above the form.

can we make list current & expired solicitations dynamically?

**Comment by mbwatson** [comment]
i'm thinking of sourcing solicitations from a yaml file like this

```
- name: "CC* 21-528"
  url: https://www.nsf.gov/pubs/2021/nsf21528/nsf21528.htm
  sortDate: 2021-10-21
  displayDate: March 01, 2021; October 11, 2021
- name: "CISE-MSI Program"
  url: https://www.nsf.gov/pubs/2021/nsf21533/nsf21533.htm?org=NSF
  sortDate: 2021-04-15
  displayDate: April 15, 2021 (April 15, annually thereafter)
  #...etc
```

then a hook (use-solicitations.js) will handle sorting solicitations into two groups&mdash;current and expired&mdash;at build time to hand off to the contact page to render dynamically in table according to each solicitation's `sortDate` property.

- solicitations source file: https://github.com/fabric-testbed/fabric-website/blob/staging/src/data/solicitations.yaml
- result: https://staging.fabric-testbed.net/get-involved

@bryttanytodd does this seem like a good solution?

@yaxue1123 your thoughts on this are welcome, too!

**Comment by bryttanytodd** [comment]
Yep, I think this makes a lot of sense.

Bryttany Todd
pronouns: she/her/hers
RENCI
University of North Carolina at Chapel Hill
100 Europa Drive, Suite 540
Chapel Hill, NC 27517-7583
