### ISSUE TITLE
Add FAB Style Guide

### ISSUE THREAD

**Issue by mbwatson** [fabric-testbed/fabric-website#39]
add these to FABRIC style guide

FAB style guide & Logos → https://whatisfabric.net/branding

**Comment by mbwatson** [comment]
staged version [here](https://staging.fabric-testbed.net/branding/logos), but clarification is needed as to which things are for FABRIC and which are for FAB?

perhaps separate pages for FABRIC and FAB resources?

**Comment by mbwatson** [comment]
@bryttanytodd we have a first draft staged. i was thinking something like [this](https://staging.fabric-testbed.net/branding), but i'm still sorting user flow in my mind.

i'll revisit this soon, but maybe you can chime in: how can this be improved so far?

**Comment by bryttanytodd** [comment]
I like this. My only two thoughts are …


  1.  do I like the FABRIC/FAB links centered? Or would I like them left justified?
  2.  Should we just have a content paragraph under Branding” and then have the respective links under the sub headers? This is more of a ponder than a suggestion. So it would look something like this…

Branding
View resources relating to FABRIC and FAB's style guidelines, including color palettes, logos, and type faces. In addition, you will find details on using these together to create components for the web, such as buttons.

Style
FABRIC
FAB

Logos
FABRIC
FAB

PR Resources
FABRIC
FAB

Bryttany Todd
pronouns: she/her/hers
RENCI
University of North Carolina at Chapel Hill
100 Europa Drive, Suite 540
Chapel Hill, NC 27517-7583
