### ISSUE TITLE
Add Past Event for Mass Open Cloud 2020

### ISSUE THREAD

**Issue by jsrjaganatha** [fabric-testbed/fabric-website#74]
Title: Mass Open Cloud 2020
Date: 2020-03-02
Location: Boston, MA
URL: https://massopen.cloud/events/2020-open-cloud-workshop/#:~:text=March%202%20%E2%80%93%203%2C%202020&text=The%20OC%20Workshop%20welcomed%20users,of%20experience%20with%20these%20efforts.
Description: The Mass Open Cloud Workshop will be held on March 2-3, 2020 at Boston University.  This year, given exciting developments associated with the MOC, the OC Workshop convened the MOC community with key stakeholders of the Open Cloud Testbed (OCT), OpenStack Foundation (OSF) Open Infra Labs (OIL) project, New England Research Cloud (NERC). FABRIC contributor Paul Ruth will present a micro-talk, titled “What is FABRIC?”
FabricHosted: false

**Comment by yaxue1123** [comment]
updated url to: https://massopen.cloud/events/2020-open-cloud-workshop/
