### ISSUE TITLE
Add Past Event for IIT Real-Time Communications Conference 2019

### ISSUE THREAD

**Issue by jsrjaganatha** [fabric-testbed/fabric-website#87]
Title: IIT Real-Time Communications Conference 2019
Date: 2019–10-14
Location: Virtual
URL: https://www.rtc-conference.com/2019/
Description: The IIT RTC Conference and Expo is a globally recognized collaborative event, where industry and academia connect. Leveraging its unique academic setting, this annual conference brings together technical professionals and business executives from the data and telecommunications industry, standards bodies, policy and regulatory institutions, and academic educators and researchers to promote an open exchange of ideas to lead future development in the rapidly changing field of real-time communications. At the event, FABRIC co-PI Anita will present "What is FABRIC?"
FabricHosted: false

**Comment by yaxue1123** [comment]
solved by[ pull request #91 ](https://github.com/fabric-testbed/fabric-website/pull/91)
